#
# This file is used to declare the list of libraries
# which are used as dependencies in the project.
# See https://docs.gradle.org/7.4.2/userguide/platforms.html#sub:central-declaration-of-dependencies
#
# For Micronaut, we have 3 kinds of dependencies:
#   - managed dependencies, which are exposed to consumers via a BOM (or version catalog)
#   - managed BOMs, which are imported into the BOM that we generate
#   - all other dependencies, which are implementation details
#
# If a library needs to appear in the BOM of the project, then it must be
# declared with the "managed-" prefix.
# If a BOM needs to be imported in the BOM of the project, then it must be
# declared with the "boms-" prefix.
# Both managed dependencies and BOMs need to have their version declared via
# a managed version (a version which alias starts with "managed-"

[versions]

# Micronaut
micronaut = "5.0.0-M8"
micronaut-test = "5.0.0-M3"

# Platform dependencies
micronaut-reactor = "4.0.0-M1"
micronaut-serde = "3.0.0-M1"

# Frameworks
awaitility = '4.3.0'

# Managed versions appear in the BOM
managed-foundationdb = "7.4.3"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

#
# Managed dependencies appear in the BOM
#
managed-foundationdb = { module = 'org.foundationdb:fdb-java', version.ref = 'managed-foundationdb' }

#
# Imported BOMs, also appearing in the generated BOM
#
micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = "micronaut-reactor" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }

# Other libraries used by the project but non managed
testcontainers = { module = "org.testcontainers:testcontainers" }
awaitility = { module = 'org.awaitility:awaitility', version.ref = 'awaitility' }

[bundles]

[plugins]
